name: Run Tests and Upload Extent Reports

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your codebase
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      # Build and run tests
      - name: Run tests
        run: ./gradlew clean test

      # Upload Extent Report as an artifact
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: ExtentReport
          path: test-output/SparkReport.html